config/routes.rb
Dropboxtestgem::Application.routes.draw do
  
  resource :dropbox
  match 'dropbox/authorize' => 'dropbox#authorize'
  match 'dropbox/listing' => 'dropbox#listing'
  match 'dropbox/search' => 'dropbox#search'
 

end

app/models/tarantula.rb
class Tarantula

  attr_accessor :dropbox

  def initialize(dropbox_client)
    @dropbox = dropbox_client
  end

  def search_dropbox(keywords)
    final_file_list = []
    file_list = crawl_storage_structure
    file_list.each do |file|
      file_content = @dropbox.download(file.path)
      keywords.each do |keyword|
        if file_content.downcase.include?(keyword.downcase)
          final_file_list << file
          save_local_copy(file.path, file_content)
        end
      end
    end

    final_file_list.uniq
  end


  private

  def save_local_copy(file_path, content)
    filename = Pathname.new(file_path).basename
    open("downloads/"+ filename.to_s, "wb") { |file|
      file.write(content)
    }
  end

  
  def crawl_storage_structure
    file_list, directory_list = [] 
    listing_data = @dropbox.metadata("/")
    directory_list = listing_data.contents.select { |resource| resource.is_dir }
    file_list = listing_data.contents.select { |resource| !resource.is_dir }
    directory_list.each do |node|
      data = @dropbox.metadata(node.path)
      directory_list.concat(data.contents.select { |resource| resource.is_dir })
      file_list.concat(data.contents.select { |resource| !resource.is_dir })
    end

    file_list
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dropbox_controller.rb
class DropboxController < ApplicationController

  before_filter :prepare_session, :except => [:authorize]
  after_filter :stash_session, :except => [:authorize]

  def authorize
   if params[:oauth_token] then
     dropbox_session = Dropbox::Session.deserialize(session[:dropbox_session])
     dropbox_session.authorize(params)
     session[:dropbox_session] = dropbox_session.serialize

     redirect_to :action => 'listing'
   else
     dropbox_session = Dropbox::Session.new(CONSUMER_KEY, CONSUMER_SECRET)
     session[:dropbox_session] = dropbox_session.serialize
     redirect_to dropbox_session.authorize_url(:oauth_callback => url_for(:action => 'authorize'))
   end
  end

  def listing
  end

  def search
    keywords = params[:q].split(",").map(&:strip)
    @data = Tarantula.new(@dropbox_session).search_dropbox(keywords)
  end

  private

  def prepare_session
    @dropbox_session = Dropbox::Session.deserialize(session[:dropbox_session])
    @dropbox_session.mode = :dropbox
  end 

  def stash_session
     session[:dropbox_session] = @dropbox_session.serialize
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dropbox/_search_section.html.erb
  <%= form_tag(dropbox_search_path, :method => "post") do %>
    <%= label_tag(:q, "Search dropbox for keywords (comma separated):") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
  <% end %>

app/views/dropbox/listing.html.erb
<html>

  <%= render "search_section" %>

</html>

app/views/dropbox/search.html.erb
<html>

  <%= render "search_section" %>

  <br />
  <% if @data.blank? %>
    No content found
  <% end%>
  <% @data.each do |file| %>
    <%= file.path %>
    <br />
  <% end %>  
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dropboxtestgem</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>